### ISSUE TITLE
Unable to extract extrinsic parameters

### ISSUE THREAD

**Issue by rahidraghav** [ccyinlu/multimodal_data_studio#2]
Error using estimateExtrinsicParametersCoMask_LM_G2O (line 46)
Invalid MEX-file

'<DIRECTORY>/multimodal_data_studio/utils/optimization/mex/EdgeSE3ProjectDirectWithDirstortG2oLMMex.mexa64':
<DIRECTORY>/multimodal_data_studio/utils/optimization/mex/EdgeSE3ProjectDirectWithDirstortG2oLMMex.mexa64:
undefined symbol: _ZN3g2o15SparseOptimizer8optimizeEib

Successfully completed extraction , but unable to perform extrinsic calibration

Please help with the matlab and ubuntu version to build the mex files.

**Comment by ccyinlu** [comment]
It seems like the link problem, you can try the following method to fix the problem:
1. preload the library before starting matlab
you could create the bash script such as `start_matlab.sh` with the following content:  
```
#!/bin/bash
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/lib \
matlab $@
```
You can start your matlab using the command `bash start_matlab.sh`  

2. install g2o correctly
As you could compile the `EdgeSE3ProjectDirectWithDirstortG2oLMMex.mexa64` correctly, which means you have installed G2O. Pay attention you have install the correct version. To avoid trouble, you better try the G2O source code within the `thirdParty` and install G2O from the source code.

3. check the library dependency
you could run the `ldd` command to check the library dependency of the mex file: 
`ldd EdgeSE3ProjectDirectWithDirstortG2oLMMex.mexa64`
You may get the following results:
```
        linux-vdso.so.1 =>  (0x00007fff9ceba000)
        libg2o_types_sba.so => /usr/local/lib/libg2o_types_sba.so (0x00007f8420cba000)
        libg2o_core.so => /usr/local/lib/libg2o_core.so (0x00007f8420a5c000)
        libg2o_stuff.so => /usr/local/lib/libg2o_stuff.so (0x00007f842083e000)
        libmx.so => not found
        libmex.so => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f84204bc000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f84201b3000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f841ff9d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f841fbd3000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f841f9cb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8421132000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f841f7ae000)
```
You can check if there's any missing denpendencies or the dependencies could be found correctly.

**You'd better try the solution 1 first, maybe your problem can be solved.**

**Comment by rahidraghav** [comment]
I have resolved the issue.. It was because i was compiling it in Matlab 2020. It works fine on Matlab 2017b  . Thanks!!!

**Comment by rahidraghav** [comment]
This issue was solved
